const all_products = [
    // Men's Products
    {
        id: 1,
        name: "Men's Long Sleeved Tee",
        category: 'men',
        image: 'men_long_sleeved_tee.png',
        newPrice: 30.0,
        oldPrice: 50.0,
    },
    {
        id: 2,
        name: "Men's Training Shorts",
        category: 'men',
        image: 'men_training_shorts.png',
        newPrice: 25.0,
        oldPrice: 40.0,
    },
    {
        id: 3,
        name: "Men's Running Jacket",
        category: 'men',
        image: 'men_running_jacket.png',
        newPrice: 60.0,
        oldPrice: 80.0,
    },
    {
        id: 4,
        name: "Men's Compression Tights",
        category: 'men',
        image: 'men_compression_tights.png',
        newPrice: 35.0,
        oldPrice: 60.0,
    },
    {
        id: 5,
        name: "Men's Hoodie",
        category: 'men',
        image: 'men_hoodie.png',
        newPrice: 50.0,
        oldPrice: 70.0,
    },
    {
        id: 6,
        name: "Men's Joggers",
        category: 'men',
        image: 'men_joggers.png',
        newPrice: 45.0,
        oldPrice: 65.0,
    },
    {
        id: 7,
        name: "Men's Tank Top",
        category: 'men',
        image: 'men_tank_top.png',
        newPrice: 20.0,
        oldPrice: 35.0,
    },
    {
        id: 8,
        name: "Men's Training Tee",
        category: 'men',
        image: 'men_training_tee.png',
        newPrice: 25.0,
        oldPrice: 40.0,
    },
    {
        id: 9,
        name: "Men's Sleeveless Hoodie",
        category: 'men',
        image: 'men_sleeveless_hoodie.png',
        newPrice: 40.0,
        oldPrice: 60.0,
    },
    {
        id: 10,
        name: "Men's Track Pants",
        category: 'men',
        image: 'men_track_pants.png',
        newPrice: 50.0,
        oldPrice: 70.0,
    },
    {
        id: 11,
        name: "Men's Performance Shorts",
        category: 'men',
        image: 'men_performance_shorts.png',
        newPrice: 30.0,
        oldPrice: 45.0,
    },
    {
        id: 12,
        name: "Men's Zip-Up Hoodie",
        category: 'men',
        image: 'men_zip_up_hoodie.png',
        newPrice: 55.0,
        oldPrice: 75.0,
    },
    {
        id: 13,
        name: "Men's Sweatshirt",
        category: 'men',
        image: 'men_sweatshirt.png',
        newPrice: 40.0,
        oldPrice: 60.0,
    },
    {
        id: 14,
        name: "Men's Gym Bag",
        category: 'men',
        image: 'men_gym_bag.png',
        newPrice: 35.0,
        oldPrice: 50.0,
    },
    {
        id: 15,
        name: "Men's Beanie",
        category: 'men',
        image: 'men_beanie.png',
        newPrice: 15.0,
        oldPrice: 25.0,
    },
    // Women's Products
    {
        id: 16,
        name: "Women's Sports Bra",
        category: 'women',
        image: 'women_sports_bra.png',
        newPrice: 25.0,
        oldPrice: 40.0,
    },
    {
        id: 17,
        name: "Women's Leggings",
        category: 'women',
        image: 'women_leggings.png',
        newPrice: 40.0,
        oldPrice: 60.0,
    },
    {
        id: 18,
        name: "Women's Crop Top",
        category: 'women',
        image: 'women_crop_top.png',
        newPrice: 30.0,
        oldPrice: 50.0,
    },
    {
        id: 19,
        name: "Women's Running Jacket",
        category: 'women',
        image: 'women_running_jacket.png',
        newPrice: 60.0,
        oldPrice: 80.0,
    },
    {
        id: 20,
        name: "Women's Training Shorts",
        category: 'women',
        image: 'women_training_shorts.png',
        newPrice: 25.0,
        oldPrice: 40.0,
    },
    {
        id: 21,
        name: "Women's Tank Top",
        category: 'women',
        image: 'women_tank_top.png',
        newPrice: 20.0,
        oldPrice: 35.0,
    },
    {
        id: 22,
        name: "Women's Zip-Up Hoodie",
        category: 'women',
        image: 'women_zip_up_hoodie.png',
        newPrice: 55.0,
        oldPrice: 75.0,
    },
    {
        id: 23,
        name: "Women's Sweatshirt",
        category: 'women',
        image: 'women_sweatshirt.png',
        newPrice: 40.0,
        oldPrice: 60.0,
    },
    {
        id: 24,
        name: "Women's Joggers",
        category: 'women',
        image: 'women_joggers.png',
        newPrice: 45.0,
        oldPrice: 65.0,
    },
    {
        id: 25,
        name: "Women's Performance Shorts",
        category: 'women',
        image: 'women_performance_shorts.png',
        newPrice: 30.0,
        oldPrice: 45.0,
    },
    {
        id: 26,
        name: "Women's Track Pants",
        category: 'women',
        image: 'women_track_pants.png',
        newPrice: 50.0,
        oldPrice: 70.0,
    },
    {
        id: 27,
        name: "Women's Sleeveless Hoodie",
        category: 'women',
        image: 'women_sleeveless_hoodie.png',
        newPrice: 40.0,
        oldPrice: 60.0,
    },
    {
        id: 28,
        name: "Women's Training Tee",
        category: 'women',
        image: 'women_training_tee.png',
        newPrice: 25.0,
        oldPrice: 40.0,
    },
    {
        id: 29,
        name: "Women's Gym Bag",
        category: 'women',
        image: 'women_gym_bag.png',
        newPrice: 35.0,
        oldPrice: 50.0,
    },
    {
        id: 30,
        name: "Women's Beanie",
        category: 'women',
        image: 'women_beanie.png',
        newPrice: 15.0,
        oldPrice: 25.0,
    },
    // Accessories
    {
        id: 31,
        name: "Water Bottle",
        category: 'accessories',
        image: 'water_bottle.png',
        newPrice: 15.0,
        oldPrice: 25.0,
    },
    {
        id: 32,
        name: "Gym Towel",
        category: 'accessories',
        image: 'gym_towel.png',
        newPrice: 10.0,
        oldPrice: 20.0,
    },
    {
        id: 33,
        name: "Yoga Mat",
        category: 'accessories',
        image: 'yoga_mat.png',
        newPrice: 35.0,
        oldPrice: 50.0,
    },
    {
        id: 34,
        name: "Resistance Bands",
        category: 'accessories',
        image: 'resistance_bands.png',
        newPrice: 20.0,
        oldPrice: 30.0,
    },
    {
        id: 35,
        name: "Weightlifting Gloves",
        category: 'accessories',
        image: 'weightlifting_gloves.png',
        newPrice: 25.0,
        oldPrice: 35.0,
    },
    {
        id: 36,
        name: "Foam Roller",
        category: 'accessories',
        image: 'foam_roller.png',
        newPrice: 30.0,
        oldPrice: 45.0,
    },
    {
        id: 37,
        name: "Skipping Rope",
        category: 'accessories',
        image: 'skipping_rope.png',
        newPrice: 15.0,
        oldPrice: 25.0,
    },
    {
        id: 38,
        name: "Gym Backpack",
        category: 'accessories',
        image: 'gym_backpack.png',
        newPrice: 45.0,
        oldPrice: 60.0,
    },
    {
        id: 39,
        name: "Shaker Bottle",
        category: 'accessories',
        image: 'shaker_bottle.png',
        newPrice: 10.0,
        oldPrice: 20.0,
    },
    {
        id: 40,
        name: "Fitness Tracker",
        category: 'accessories',
        image: 'fitness_tracker.png',
        newPrice: 70.0,
        oldPrice: 100.0,
    },
    {
        id: 41,
        name: "Ankle Weights",
        category: 'accessories',
        image: 'ankle_weights.png',
        newPrice: 25.0,
        oldPrice: 35.0,
    },
    {
        id: 42,
        name: "Gym Socks",
        category: 'accessories',
        image: 'gym_socks.png',
        newPrice: 10.0,
        oldPrice: 15.0,
    },
    {
        id: 43,
        name: "Sweatbands",
        category: 'accessories',
        image: 'sweatbands.png',
        newPrice: 8.0,
        oldPrice: 12.0,
    },
    {
        id: 44,
        name: "Kettlebell",
        category: 'accessories',
        image: 'kettlebell.png',
        newPrice: 50.0,
        oldPrice: 70.0,
    },
    {
        id: 45,
        name: "Pull-Up Bar",
        category: 'accessories',
        image: 'pull_up_bar.png',
        newPrice: 60.0,
        oldPrice: 80.0,
    },
];

export default all_products;
